spring:
  application:
    name: check-bus
  config:
    import: ${key.env.path}
  datasource:
    url: ${key.datasource.url}
    username: ${key.datasource.username}
    password: ${key.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

dodam-api-url: ${key.dodam-api-url}

dauth:
  client-url: ${key.dauth.client-url}
  open-dodam-url: ${key.dauth.open-dodam-url}
  client-id: ${key.dauth.client-id}
  client-secret: ${key.dauth.client-secret}

jwt:
  secret-key: ${key.jwt.secret-key}
